### PR TITLE
Propagate HistoryResponse error messages

### PR DESCRIPTION
**Pull request by bmario**
This adds handling for the HistoryResponse error message for the HistoryClient in "master".

### CODE REVIEW

**Comment by tilsche** [comment]
While we're at error messages: Should there also be warnings? E.g. by having both values *and* a message simultaneously?

I don't have a strong opinion about that, but at least it should be defined. I do see a use case for adding some warning message to a valid result.

**Comment by tilsche** [comment]
I think it makes sense to define default behavior in the base class... which is probably "log it and eat it up".

**Comment by bmario** [comment]
> I think it makes sense to define default behavior in the base class... which is probably "log it and eat it up".

Does it though? The currently only existing `HistoryClient` implementation (`DummyHistory`) doesn't use that behavior.

**Comment by tilsche** [comment]
> > I think it makes sense to define default behavior in the base class... which is probably "log it and eat it up".
> 
> Does it though? The currently only existing `HistoryClient` implementation (`DummyHistory`) doesn't use that behavior.

On second thought, you're right. Keep as is.

**Pull request merged**
